DROP SCHEMA ProyectoFinal;

CREATE DATABASE ProyectoFinal;

USE ProyectoFinal;

CREATE TABLE Gerente(
	Codigo VARCHAR(20) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Turno VARCHAR(15) NOT NULL,
	DPI VARCHAR(13) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Sexo VARCHAR(15) NOT NULL,
	Contraseña VARCHAR(50),
	PRIMARY KEY (Codigo)
);

CREATE TABLE Cajero(
	Codigo VARCHAR(20) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Turno VARCHAR(15) NOT NULL,
	DPI VARCHAR(13) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Sexo VARCHAR(15) NOT NULL,
	Contraseña VARCHAR(50),
	PRIMARY KEY (Codigo)
);

CREATE TABLE Cliente(
	Codigo VARCHAR(20) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	DPI VARCHAR(13) NOT NULL,
	Nacimiento DATE NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	Sexo VARCHAR(15) NOT NULL,
	Contraseña VARCHAR(50),
	PRIMARY KEY (Codigo)
);

CREATE TABLE Cuenta(
	Codigo VARCHAR(20) NOT NULL,
	Creacion DATE NOT NULL,
	Credito FLOAT NOT NULL,
	Codigo_Cliente VARCHAR(20) NOT NULL,
	PRIMARY KEY (Codigo),
	FOREIGN KEY (Codigo_Cliente) REFERENCES Cliente(Codigo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Transaccion(
	Codigo INT(20) NOT NULL AUTO_INCREMENT,
	Codigo_Cuenta VARCHAR(20) NOT NULL,
	Fecha DATE NOT NULL,
	Hora VARCHAR(10) NOT NULL,
	Tipo VARCHAR(20) NOT NULL,
	Monto FLOAT NOT NULL,
	Codigo_Cajero VARCHAR(20) NOT NULL,
	PRIMARY KEY (Codigo),
	FOREIGN KEY (Codigo_Cuenta) REFERENCES Cuenta(Codigo) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (Codigo_Cajero) REFERENCES Cajero(Codigo) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Historial(
	ID INT(20) NOT NULL AUTO_INCREMENT,
	Codigo_Gerente VARCHAR(20) NOT NULL,
	Entidad VARCHAR(20) NOT NULL,
	Descripcion VARCHAR(150) NOT NULL,
	Fecha DATE NOT NULL,
	PRIMARY KEY (ID),
	FOREIGN KEY (Codigo_Gerente) REFERENCES Gerente(Codigo) ON DELETE CASCADE ON UPDATE CASCADE
);

